language: python
dist: xenial

branches:
  only:
  - master

matrix:
  include:
    # Node 8
    - python: 3.7
      env:  TRAVIS_NODE_VERSION=8
    # Node 10
    - python: 3.7
      env:  TRAVIS_NODE_VERSION=10
    # Node 12
    # Py 2.7, 3.5-3.7
    - python: 2.7
      env:  TRAVIS_NODE_VERSION=12
    - python: 3.5
      env:  TRAVIS_NODE_VERSION=12
    - python: 3.6
      env:  TRAVIS_NODE_VERSION=12
    - python: 3.7
      env:  TRAVIS_NODE_VERSION=12
    - python: 3.8-dev
      env:  TRAVIS_NODE_VERSION=12
  allow_failures:
    - python: 3.8-dev
      env:  TRAVIS_NODE_VERSION=12

cache:
  directories:
    - lektor/admin/node_modules

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - mkdir -p local/bin
  - pushd local/bin
  - wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
  - tar -xf ffmpeg-release-amd64-static.tar.xz --strip-components 1 --wildcards "*/ffmpeg" "*/ffprobe"
  - rm ffmpeg-release-amd64-static.tar.xz
  - popd
  - export LEKTOR_RESOURCES=$(pwd)

install:
  - travis_retry pip install --upgrade pytest
  - travis_retry pip install --upgrade codecov
  - travis_retry pip install --editable .[test]
  - travis_retry make build-js

before_script:
  - python --version
  - pip list
  - node --version
  - npm --version
  - $LEKTOR_RESOURCES/local/bin/ffmpeg -version

script: make coverage

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f0c538cdfc9883f81e34
